### ISSUE TITLE
ModuleNotFoundError: No module named 'optimization'

### ISSUE THREAD

**Issue by zhangtuo1999** [zenhjunpro/ASTEN#1]
```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    from ATSEN import RobertaForTokenClassification_Modified
  File "/home/tourry/code/ATSEN/ATSEN.py", line 7, in <module>
    from optimization import find_optimal_svm
ModuleNotFoundError: No module named 'optimization'
```

**Comment by XiaoHong0-0** [comment]
> ```
> Traceback (most recent call last):
>   File "main.py", line 31, in <module>
>     from ATSEN import RobertaForTokenClassification_Modified
>   File "/home/tourry/code/ATSEN/ATSEN.py", line 7, in <module>
>     from optimization import find_optimal_svm
> ModuleNotFoundError: No module named 'optimization'
> ```

请问问题解决了嘛

**Comment by XiaoHong0-0** [comment]
> ```
> Traceback (most recent call last):
>   File "main.py", line 31, in <module>
>     from ATSEN import RobertaForTokenClassification_Modified
>   File "/home/tourry/code/ATSEN/ATSEN.py", line 7, in <module>
>     from optimization import find_optimal_svm
> ModuleNotFoundError: No module named 'optimization'
> ```
请问问题解决了嘛

**Comment by zenhjunpro** [comment]
sorry，I forgot to upload, already patched up！You can try again.
